### ISSUE TITLE
Setting a mock result longer than 28K freezes phiremock in debug mode

### ISSUE THREAD

**Issue by michaelarnauts** [mcustiel/phiremock#32] opened 2018-01-22 15:29 UTC
When you set a mock result longer than 28K chars, phiremock hangs, but only in debug mode. I assume this is due to an issue with the log writing code.

EDIT: it seems to be related to a total size of all `expectARequestToRemoteServiceWithAResponse` calls.

**Comment by michaelarnauts** [comment] 2018-01-22 15:44
Hmm, I was just trying to reproduce this again, but I'm not sure it's related to long responses. When I do two `$I->expectARequestToRemoteServiceWithAResponse(` calls in one Cest, the 2nd seems to hang.

**Comment by mcustiel** [comment] 2018-01-22 19:30
Could you find when the problem occurs? I could not reproduce none of the two cases. Just added tests for them, one that creates 4 expectations in one Cest and one that sends a video as a response.

**Comment by mcustiel** [comment] 2018-01-23 07:34
You mentioned in your first comment the log writing, and I noticed that the debug mode takes longer because of that. It seems to be related to the symfony process event handler used to get the output from phiremock. Will try to take that path to see if it can be improved.

**Comment by michaelarnauts** [comment] 2018-01-23 09:46
Do your tests also run fine in debug mode? I'll try to debug a bit further and see if I can find a way to reproduce the issue more easily.

**Comment by michaelarnauts** [comment] 2018-01-23 10:03
This Cest doesn't work on my system when phiremock is running in debug mode.

When a second `expectARequestToRemoteServiceWithAResponse` block is added, it is counted to the total that phiremock can handle. Even a response of a single space isn't accepted anymore if a previous response was already 60629 bytes.

```php
<?php

use Mcustiel\Phiremock\Client\Phiremock;
use Mcustiel\Phiremock\Client\Utils\A;
use Mcustiel\Phiremock\Client\Utils\Is;
use Mcustiel\Phiremock\Client\Utils\Respond;

class AaaaCest
{
    /**
     * @param FunctionalTester $I
     */
    public function checkStatus($I)
    {

        // 60629 works, 60630 doesn't work
        $response = str_repeat(' ', 60630);
        $I->expectARequestToRemoteServiceWithAResponse(
            Phiremock::on(
                A::postRequest()->andUrl(Is::equalTo('/one'))
            )->then(
                Respond::withStatusCode(200)->andBody($response)
            )
        );
    }
}
```

**Comment by mcustiel** [comment] 2018-01-23 19:53
The problem is related to the way symfony/process handles the output from the running process. 
https://github.com/symfony/symfony/issues/17390
Will investigate how this problem can be solved.

**Comment by michaelarnauts** [comment] 2018-01-24 10:03
Thanks! But in this case, it's already triggered at 64KB?

**Comment by mcustiel** [comment] 2018-01-24 10:34
It seems so. I removed the output callback from the start method and disabled the output from symfony process and the problem is gone.

**Comment by mcustiel** [comment] 2018-01-24 19:12
Phiremock 1.7.3 + Phiremock Codeception Extension 1.5.3 should solve this problem. Please check if it works for you. In that case I will close the issue.

**Closed as completed** 2018-01-27 10:38 UTC
